# Generated by Django 3.1.2 on 2020-10-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='app_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.timeslots'),
        ),
    ]
